name: Push Event Workflow

on: push

jobs:
  unit-testing:
    runs-on: macos-latest

    steps:
    - name : Checkout code
      uses : actions/checkout@v2

    - name : Install Packages
      run : pip install -r requirements.txt

    - name : Run tests
      run : pytest test/