name: Push Event Workflow

on: push

jobs:
  unit-testing-windows:
    name : Windows tests
    runs-on: windows-latest
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
    - name : Install Packages
      run : pip install -r requirements.txt
    - name : Run Windows tests
      run : pytest test/